Update workflow action versions
Also build everything in one step

diff --git a/.github/workflows/build-nix.yml b/.github/workflows/build-nix.yml
--- a/.github/workflows/build-nix.yml
+++ b/.github/workflows/build-nix.yml
@@ -9,52 +9,36 @@ jobs:
   build-nix:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v6
       - uses: cachix/install-nix-action@v31
         with:
           nix_path: nixpkgs=channel:nixos-unstable
-      - uses: cachix/cachix-action@v14
+      - uses: cachix/cachix-action@v16
         with:
           name: skyenet
           authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
-      - name: Build Porkbun-DDNS
+      - name: Build packages
         run: |
-          nix build ./NixOS#porkbun-ddns
-      - name: Build recutils
-        run: |
-          nix build ./NixOS#recutils
-      - name: Build anemoi
-        run: |
-          nix build ./NixOS#anemoi
-      - name: Build ambient-ci
-        run: |
-          nix build ./NixOS#ambient-ci
-      - name: Build radicle-ci-ambient
-        run: |
-          nix build ./NixOS#radicle-ci-ambient
-      - name: Build CDash
-        run: |
-          nix build ./NixOS#cdash
-      - name: Build NetworkManager-clat
-        run: |
-          nix build ./NixOS#networkmanager-clat
-      # - name: Build Tube Archivist
-      #   run: |
-      #     nix build ./NixOS#tubearchivist
-      # - name: Build Browsertrix Crawler
-      #   run: |
-      #     nix build ./NixOS#browsertrix-crawler
+          nix build ./NixOS#ambient-ci          || echo "ERROR!"
+          nix build ./NixOS#anemoi              || echo "ERROR!"
+          nix build ./NixOS#cdash               || echo "ERROR!"
+          nix build ./NixOS#networkmanager-clat || echo "ERROR!"
+          nix build ./NixOS#porkbun-ddns        || echo "ERROR!"
+          nix build ./NixOS#radicle-ci-ambient  || echo "ERROR!"
+          nix build ./NixOS#recutils            || echo "ERROR!"
+        # nix build ./NixOS#tubearchivist       || echo "ERROR!"
+        # nix build ./NixOS#browsertrix-crawler || echo "ERROR!"
   build-nix-macos:
     runs-on: macos-latest
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v6
       - uses: cachix/install-nix-action@v31
         with:
           nix_path: nixpkgs=channel:nixos-unstable
-      - uses: cachix/cachix-action@v14
+      - uses: cachix/cachix-action@v16
         with:
           name: skyenet
           authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
-      - name: Build recutils
+      - name: Build packages
         run: |
-          nix build ./NixOS#recutils
+          nix build ./NixOS#recutils || echo "ERROR!"
